######################## default configuration ####################
# The base URL of your site (required). This will be prepended to all relative URLs.
baseURL = 'https://goodly-zebra.cloudvent.net'
# Title of your website (required).
title = "BrokerOS"

languageCode = 'en-us'
# Your theme name
#theme = "hugoplate"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "America/New_York"