# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Hero - Background Image and Buttons"
  description: Heading, text, image & colored button.
  icon: "cottage"
  tags:
    - Heading
    - Text
    - Image
    - Buttons
  remove_extra_inputs: true 

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: '--bos-color-primary'
  background_color_dark: '--bos-color-primary-dark'
  background_image:
    image_path: /images/bos-defaults/heroes/truck-on-bridge-2160w-1440h.png
    alt_text: >-
      An illustration of someone leaning on one leg while facing us, next to a
      laptop that comes up their waist. One of their hands is on the back of
      the laptop, and one is in their pocket. On the laptop screen is an
      illustration of the world.
    border_color: '--bos-color-on-container-dark'
  announcement:
    announcement_text: We deliver excellence.
    text_color: '--bos-color-on-surface-dark'
    text_color_dark: '--bos-color-on-surface'
  heading:
    heading_text: Get ready to see what excellence in logistics looks like.
    text_color: '--bos-color-on-surface-dark'
    text_color_dark: '--bos-color-on-surface-dark'
  subheading:
    subheading_text: Schedule a consultation today.
    text_color: '--bos-color-on-surface-dark'
    text_color_dark: '--bos-color-on-surface-dark'
  buttons:
    - _bookshop_name: buttons/tailwindui-primary
      button_text: Get Started
      button_link: /contact
      button_aria_label: Get Started button.
      background_color: '--bos-color-on-container'
      hover_brightness: 0.85
      text_color: '--bos-color-on-surface-dark'
      background_color_dark: '--bos-color-on-container-dark'
      hover: '--bos-color-container-variant-dark'
      hover_dark: '--bos-color-container-variant'
      text_color_dark: '--bos-color-on-surface'
    - _bookshop_name: buttons/tailwindui-arrow
      button_text: Learn More
      button_icon: custom-icon-cloudcannon
      button_link: https://www.cloudcannon.com
      button_aria_label: Learn more button
      background_color: '--color-white'
      hover_brightness: 0.85
      text_color: '--bos-color-on-surface-dark'
      hover: '--bos-color-container-variant-dark'
      hover_dark: '--bos-color-container-variant'
      text_color_dark: '--bos-color-on-surface-dark'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
