# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Simple page header with gradient background"
  description: Heading, text & gradient background.
  icon: "cottage"
  tags:
    - Heading
    - Text
  remove_extra_inputs: true 

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: '--bos-color-surface'
  background_color_dark: '--bos-color-surface-dark'
  background_gradient:
    from_color: '--bos-color-primary'
    to_color: '--bos-color-container'
  heading:
    heading_text: Get ready to see what excellence in logistics looks like.
    text_color: '--bos-color-on-surface'
    text_color_dark: '--bos-color-on-surface-dark'
  subheading:
    subheading_text: We serve the world's most demanding shippers.
    text_color: '--bos-color-on-surface-variant'
    text_color_dark: '--bos-color-on-surface-dark'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
