# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Hero - Image and Form"
  description: Heading, text, image & colored button.
  icon: "cottage"
  tags:
    - Heading
    - Text
    - Image
    - Buttons
  remove_extra_inputs: true 

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: '--bos-color-container'
  background_color_dark: '--bos-color-container-dark'
  background_image:
    image_path: /images/bos-defaults/cta/truck-in-desert-1280w.jpg
    alt_text: >-
      A photo of a semi driving down the road.
    border_color: --bos-color-on-container-dark
  announcement:
    announcement_text: We deliver excellence.
    text_color: '--bos-color-on-surface'
    text_color_dark: '--bos-color-on-surface-dark'
  heading:
    heading_text: Get ready to see what excellence in logistics looks like.
    text_color: '--bos-color-on-surface'
    text_color_dark: '--bos-color-on-surface-dark'
  subheading:
    subheading_text: Schedule a consultation today.
    text_color: '--bos-color-on-surface'
    text_color_dark: '--bos-color-on-surface-dark'
  form:
    placeholder: you@example.com
    form_action: '#'
  buttons:
    - _bookshop_name: buttons/tailwindui-primary
      button_text: Get Started
      button_link: /contact
      button_aria_label: Get Started button.
      background_color: '--bos-color-on-container'
      background_color_dark: '--bos-color-on-container-dark'
      hover: '--bos-color-container-variant-dark'
      hover_dark: '--bos-color-container-variant'
      text_color: '--bos-color-on-surface-dark'
      text_color_dark: '--bos-color-on-surface'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
