# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Hero - Simple Centered with Announcement"
  description: Simple header with gradient background.
  icon: cottage
  tags:
    - Heading
    - Hero
    - CTA
    - Buttons
  remove_extra_inputs: true 

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: '--bos-color-surface'
  background_color_dark: '--bos-color-surface-dark'
  background_gradient:
    from_color: '--bos-color-primary'
    to_color: '--bos-color-container'
  announcement:
    buttons: 
    - _bookshop_name: buttons/button-tailwindui-announcement
      announcement_text: We now ship heavy haul loads!
      announcement_text_color: '--bos-color-on-surface'
      announcement_text_color_dark: '--bos-color-on-surface-dark'
      button_text: Learn More
      button_link: https://www.brokeros.com
      button_text_color: '--bos-color-on-surface'
      hover: '--bos-color-container-variant-dark'
      hover_dark: '--bos-color-container-variant'
      button_text_color_dark: '--bos-color-on-surface-dark'
      button_aria_label: Learn more button
  heading:
    heading_text: We Make Ship Happen
    text_color: '--bos-color-on-surface'
    text_color_dark: '--bos-color-on-surface-dark'
  subheading:
    subheading_text: We serve the world's most demanding shippers.
    text_color: '--bos-color-on-surface-variant'
    text_color_dark: '--bos-color-on-surface-dark'
  buttons:
      - _bookshop_name: buttons/tailwindui-primary
        button_text: Get Started
        button_link: /contact
        button_aria_label: Get Started button.
        background_color: '--bos-color-on-container'
        hover_brightness: 0.85
        text_color: '--bos-color-on-surface-dark'
        background_color_dark: '--bos-color-on-container-dark'
        hover: '--bos-color-container-variant-dark'
        hover_dark: '--bos-color-container-variant'
        text_color_dark: '--bos-color-on-surface'
      - _bookshop_name: buttons/tailwindui-arrow
        button_text: Learn More
        button_icon: custom-icon-cloudcannon
        button_link: https://www.cloudcannon.com
        button_aria_label: Learn more button
        background_color: '--color-white'
        hover_brightness: 0.85
        text_color: '--bos-color-on-surface'
        hover: '--bos-color-container-variant-dark'
        hover_dark: '--bos-color-container-variant'
        text_color_dark: '--bos-color-on-surface-dark'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
